Models for Airbus A380, Gulfstream G550, and  MD90
OpenMDAO/Aviary_Community pull request #4
Opened 2024-08-03 00:55 UTC by tahaitani

All models run with SLSQP optimizer

2024-08-08 15:56 UTC, ehariton approved these changes

2024-08-12 21:18 UTC, jkirk5 requested changes
just some minor formatting requests

2024-08-12 21:18 UTC, jkirk5 commented on Gulfstream G550/G550.csv
> +,,,
clean up extra commas

2024-08-12 21:18 UTC, jkirk5 commented on MD90/MD90.csv
> +aircraft:air_conditioning:mass_scaler,1,unitless,,
also extra commas in this file

2024-08-15 14:03 UTC, tahaitani commented on Gulfstream G550/G550.csv
> +,,,
Fixed

2024-08-15 14:04 UTC, tahaitani commented on MD90/MD90.csv
> +aircraft:air_conditioning:mass_scaler,1,unitless,,
Fixed and removed all extra commas

2024-08-22 18:05 UTC, jkirk5 approved these changes

2024-08-22 18:05 UTC, merged